"""empty message

Revision ID: d39ae5c05092
Revises: 
Create Date: 2022-07-24 21:52:58.483171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd39ae5c05092'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('livres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isbn', sa.String(length=50), nullable=False),
    sa.Column('titre', sa.String(length=50), nullable=False),
    sa.Column('dateparution', sa.DateTime(), nullable=False),
    sa.Column('editeur', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('categorie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categorie_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('livres')
    op.drop_table('categories')
    # ### end Alembic commands ###
